name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # Change this to your default branch if different
  schedule:
    - cron: '0 0 * * 0'  # Weekly at midnight on Sunday

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r HuggingFace/requirements.txt
          pip install huggingface_hub

      - name: Login to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "from huggingface_hub import login; login('$HF_TOKEN')"

      - name: Prepare and deploy to Hugging Face Spaces
        env:
          HF_SPACE_NAME: ${{ secrets.HF_SPACE_NAME }}
        run: |
          # Create a temporary directory for deployment
          mkdir -p deploy_temp
          
          # Copy HuggingFace files
          cp -r HuggingFace/* deploy_temp/
          
          # Copy project files needed by the API
          mkdir -p deploy_temp/Core
          mkdir -p deploy_temp/Data/Database
          mkdir -p deploy_temp/Pattern
          mkdir -p deploy_temp/Colab
          
          cp -r Core/* deploy_temp/Core/
          cp -r Data/Database/* deploy_temp/Data/Database/
          cp -r Pattern/* deploy_temp/Pattern/
          cp -r Colab/*.py deploy_temp/Colab/
          
          # Update API endpoint in configuration if needed
          # echo "api_url = https://$HF_SPACE_NAME.hf.space" >> deploy_temp/config.ini
          
          # Deploy to Hugging Face Space
          cd deploy_temp
          python -c "from huggingface_hub import HfApi; HfApi().upload_folder(folder_path='.', repo_id='$HF_SPACE_NAME', repo_type='space')"
          
          echo "Deployment to Hugging Face Spaces complete!"
